# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_VVDN_MFCS_T4240) += t4240mfcs-so.dtb
dtb-$(CONFIG_SGY_CTS1000) += cts1000.dtb

dtb-$(CONFIG_OF_ALL_DTBS) := $(patsubst $(src)/%.dts,%.dtb, $(wildcard $(src)/*.dts))
